### ISSUE TITLE
集成sso插件异常

### ISSUE THREAD

**Issue by wufengbin** [YMFE/yapi-plugin-qsso#3]
[error] D:/nodejs/node_global/~/ykit/~/buffer/index.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "D:\\nodejs\\node_global\\node_modules\\ykit\\node_modules\\buffer"
    at D:\nodejs\node_global\my-yapi\vendors\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (D:\nodejs\node_global\my-yapi\vendors\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (D:\nodejs\node_global\my-yapi\vendors\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (D:\nodejs\node_global\my-yapi\vendors\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\nodejs\node_global\my-yapi\vendors\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\nodejs\node_global\my-yapi\vendors\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\nodejs\node_global\my-yapi\vendors\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\nodejs\node_global\my-yapi\vendors\node_modules\babel-loader\lib\index.js:46:20)
    at D:\nodejs\node_global\my-yapi\vendors\node_modules\babel-loader\lib\fs-cache.js:79:18
 @ ./~/btoa/index.js 1:0-71

**Comment by 18Yi** [comment]
感觉他们这个插件系统很有问题 -- 那个ykit很多bug  插件安装的时候各种报错bug

**Comment by djhwyh** [comment]
为适配我们用的SSO的具体参数情况，我对类似插件进行了修改，有类似需求的可以参考下，网址是https://blog.csdn.net/djhemc/article/details/101355249
